### PR TITLE
Move to single plugin

### LINKED ISSUE #1: Make it a single plugin
__What should we do?__

Currently, there are two different plugins serving different use cases

* create a React extension
* create a Properties Panel extension

Considering possible other use cases that might pop up in the future, we should make this project offer _a single_ plugin that is configurable but still offers the same use cases.

I can imagine something like

```js
// webpack.config.js
const ModelerPlugin = require("camunda-modeler-webpack-plugins");

module.exports = {
  plugins: [
    new ModelerPlugin({
      type: 'react',
      loader: false,
      alias: true
    })
  ]
};
```

Cf. also to what plugin types we support: https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/

__Why should we do it?__

Make things easiest as possible for our users to use. They shouldn't care which plugin to import.

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #1

Re-structures the project to deliver a single plugin for all use cases. Use the `type` property to only append specific configuration (`react` and `propertiesPanel`). 

As with most other webpack plugins, this should go with zero-configuration as well. In this case, it simply appends all configuration

```js
const ModelerPlugin = require('camunda-modeler-webpack-plugin');

// simple
module.exports = {
  plugins: [
    new ModelerPlugin()
  ]
};

// use config, limit append
module.exports = {
  plugins: [
    new ModelerPlugin({
      type: 'propertiesPanel',
      propertiesPanelLoader: false,
      propertiesPanelAlias: true
    })
  ]
};
```

Examples:
* https://github.com/camunda/camunda-modeler-process-io-specification-plugin/pull/15
* https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/pull/87

### CODE REVIEW

**Comment by barmac** [comment]
How do I configure this to work with my UI extension which provides additional properties panel entries? Do I need to provide the plugin twice?

```js
module.exports = {
  plugins: [
    new ModelerPlugin({
      type: 'propertiesPanel'
    }),

    // react
    new ModelerPlugin()
  ]
};
```

**Comment by nikku** [comment]
Could you help me to understand one thing: Why don't we always enable all features of this plug-in? Why do I explicitly need to mark this as a _client_ or _propertiesPanel_ plug-in?

**Comment by pinussilvestrus** [comment]
> How do I configure this to work with my UI extension which provides additional properties panel entries? Do I need to provide the plugin twice?
> 
> ```js
> module.exports = {
>   plugins: [
>     new ModelerPlugin({
>       type: 'propertiesPanel'
>     }),
> 
>     // react
>     new ModelerPlugin()
>   ]
> };
> ```
> 
> If it is so, I think we should (try to) change the configuration so that I can make it work with a single plugin instance.

I would state that this isn't currently a use case the plugin provides. You could also argue that a plugin should extend a single point in the Modeler, therefore it should serve one specific use case. That's open for discussion though.

**Comment by pinussilvestrus** [comment]
> Could you help me to understand one thing: Why don't we always enable all features of this plug-in? Why do I explicitly need to mark this as a _client_ or _propertiesPanel_ plug-in?

As a Modeler plugin creator, I wouldn't want a plugin to bloat my webpack config. If I only extend the UI via react component, I don't want to have properties panel aliases to be included. If I only add some entries to the properties panel, I don't want to have a babel-loader that defines `preset-react` included.

If our assumption is that most plugins will anyway serve multiple extension points, we could argue that we should enable all stuff **per default** (also related to https://github.com/camunda/camunda-modeler-webpack-plugin/pull/2#issuecomment-1096668480). From the plugin I saw so far I got the impression that this isn't the case.

Some examples:
* https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/blob/main/webpack.config.js - Extend via client extension
* https://github.com/camunda/camunda-modeler-process-io-specification-plugin/blob/master/webpack.config.js - Extend the properties panel
* https://github.com/FlowSquad/camunda-modeler-i18n-plugin/blob/develop/webpack.config.js - Extend via client extension

**Comment by nikku** [comment]
I'd personally consider ease of use most important (it should just work, out of the box). I could otherwise simply create the webpack rules myself.

Everything else is optimization and we can consider opting out of certain features (if plug-ins become huge). That is my take on this. We have to consider that plug-in development is already hard enough (for most people).

**Comment by pinussilvestrus** [comment]
Thanks for your feedback :heart: I gave it a second thought and I agree now that the _default_ should be:
* zero config
* append [all configs](https://github.com/camunda/camunda-modeler-webpack-plugin/tree/1-single-plugin/src/config), no matter which use case is present (until it doesn't make sense, e.g. configs conflict each other)

This totally fits into our design principles ([less is more](https://github.com/bpmn-io/design-principles#less-is-more)). In the end, I shouldn't care, it should just work. Configuration can be then added for optimization. 

This makes it also possible / easier to provide what @barmac suggested (https://github.com/camunda/camunda-modeler-webpack-plugin/pull/2#issuecomment-1096668480). I will update the plugin accordingly.

**Comment by pinussilvestrus** [comment]
Implemented via https://github.com/camunda/camunda-modeler-webpack-plugin/pull/2/commits/e74af67696d30b26e884885b0d29a34fb6e55307

```js
const ModelerPlugin = require('camunda-modeler-webpack-plugin');

// default: append all
module.exports = {
  plugins: [
    new ModelerPlugin()
  ]
};
```

Ready for review again

**Comment by pinussilvestrus** [comment]
Examples to see how it works:
* https://github.com/camunda/camunda-modeler-process-io-specification-plugin/pull/15
* https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/pull/87

**Review by nikku — APPROVED** [review]
Good job.

**Pull request merged**
